apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: webapp-demo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webapp-files-volume
          mountPath: /usr/share/nginx/html 
      volumes:
      - name: webapp-files-volume
        configMap:
          name: webapp-files

